from __future__ import annotations

import base64
import os
import tempfile
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Annotated, Any

from dotenv import load_dotenv
load_dotenv(Path(__file__).parent / ".env")   # must run before any other local import

# ---------------------------------------------------------------------------
# Cloud credentials — decode GOOGLE_CREDENTIALS_JSON (base64) if present.
# Needed on Railway / Docker where there is no local service-account file.
# ---------------------------------------------------------------------------
_creds_b64 = os.environ.get("GOOGLE_CREDENTIALS_JSON", "")
if _creds_b64 and not os.path.isfile(os.environ.get("GOOGLE_APPLICATION_CREDENTIALS", "")):
    _tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".json", mode="w")
    _tmp.write(base64.b64decode(_creds_b64).decode())
    _tmp.close()
    os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = _tmp.name

from fastapi import Depends, FastAPI, HTTPException, Query, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field
from starlette.middleware.base import BaseHTTPMiddleware

import agent as agent_module
import firestore_service as fs
from auth import (
    CurrentUser, get_current_user, require_role,
    list_firebase_users, set_user_role, delete_firebase_user,
)

# ---------------------------------------------------------------------------
# App
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Chatbot Transporte Perú API",
    description="API REST para el asistente de transporte aéreo y terrestre en Perú.",
    version="2.0.0",
)


class _NoCacheHtmlMiddleware(BaseHTTPMiddleware):
    """Inject no-cache headers on HTML responses so browsers always fetch the latest index.html."""
    async def dispatch(self, request, call_next):
        response = await call_next(request)
        if "text/html" in response.headers.get("content-type", ""):
            response.headers["Cache-Control"] = "no-store, no-cache, must-revalidate"
        return response

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,   # Bearer token, no cookies — "*" requiere False
    allow_methods=["GET", "POST", "PUT", "DELETE", "OPTIONS"],
    allow_headers=["Authorization", "Content-Type"],
)

# ---------------------------------------------------------------------------
# Schemas
# ---------------------------------------------------------------------------

class ChatRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=4000)
    chat_id: str | None = Field(default=None)


class ChatResponse(BaseModel):
    reply: str
    chat_id: str
    tokens_used: int
    used_search: bool


class ChatListResponse(BaseModel):
    chats: list[dict[str, Any]]
    total_chats: int


class ChatHistoryResponse(BaseModel):
    messages: list[dict[str, Any]]
    chat_id: str


class HistoryResponse(BaseModel):
    messages: list[dict[str, Any]]
    total_messages: int


class DeleteResponse(BaseModel):
    message: str


class ProfileResponse(BaseModel):
    cliente_id: str
    nombre: str
    email: str
    preferencias: list[str]
    notas: str
    fecha_ultimo_ingreso: str | None


class ProfileUpdateRequest(BaseModel):
    nombre: str | None = Field(default=None, max_length=200)
    preferencias: list[str] | None = None
    notas: str | None = Field(default=None, max_length=2000)


class AdminSessionsResponse(BaseModel):
    sessions: list[dict[str, Any]]
    total_sessions: int


class AdminUsersResponse(BaseModel):
    users: list[dict[str, Any]]
    total_users: int


class UserRoleUpdateRequest(BaseModel):
    role: str | None = Field(default=None, description="Rol a asignar. None para quitar el rol.")


class HealthResponse(BaseModel):
    status: str
    timestamp: str


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.get("/health", response_model=HealthResponse, tags=["system"])
def health() -> HealthResponse:
    """Public health-check endpoint. No authentication required."""
    return HealthResponse(
        status="ok",
        timestamp=datetime.now(timezone.utc).isoformat(),
    )


@app.post(
    "/chat",
    response_model=ChatResponse,
    tags=["chat"],
    dependencies=[Depends(require_role(["assistant_user", "admin"]))],
)
def chat(
    body: ChatRequest,
    user: CurrentUser,
) -> ChatResponse:
    """Send a message to the agent and persist both turns to Firestore.

    Requires role: ``assistant_user`` or ``admin``.
    """
    uid = user["uid"]
    # chat_id is date-based (YYYYMMDD_HHmmss_mmm), generated by frontend on "New Chat"
    chat_id = body.chat_id or datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S_000")

    # Update last login timestamp
    fs.touch_last_login(uid=uid, email=user.get("email", ""))

    # Retrieve history for this specific chat (conversation context)
    history = fs.get_chat_messages(uid, chat_id)

    # Run the agent
    result = agent_module.run_agent(message=body.message, history=history)

    reply: str = result["response"]
    tokens: int = result["tokens_used"]
    used_search: bool = result["used_search"]

    if reply.startswith("Lo siento, ocurrió un error"):
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="El agente no pudo procesar la consulta. Intenta de nuevo.",
        )

    try:
        fs.save_chat_message(uid=uid, chat_id=chat_id, role="user", content=body.message, tokens=0)
        fs.save_chat_message(uid=uid, chat_id=chat_id, role="assistant", content=reply, tokens=tokens)
    except Exception as exc:
        print(f"[main] Firestore write error: {exc}")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="No se pudo guardar el historial. El mensaje fue procesado.",
        )

    return ChatResponse(
        reply=reply,
        chat_id=chat_id,
        tokens_used=tokens,
        used_search=used_search,
    )


@app.get(
    "/history",
    response_model=HistoryResponse,
    tags=["chat"],
    dependencies=[Depends(require_role(["assistant_user", "viewer", "admin"]))],
)
def get_history(
    user: CurrentUser,
    uid: Annotated[str | None, Query(description="UID objetivo (admin/viewer pueden inspeccionar cualquier sesión)")] = None,
) -> HistoryResponse:
    """Return the full message history for a user session.

    - ``assistant_user``: always receives their own history (``uid`` param ignored).
    - ``viewer`` / ``admin``: can pass a ``uid`` query param; defaults to own history.
    """
    role = user.get("role")
    target_uid: str

    if role == "assistant_user":
        target_uid = user["uid"]
    elif uid:
        target_uid = uid
    else:
        # admin/viewer with no uid → show own history
        target_uid = user["uid"]

    try:
        messages = fs.get_session_history(target_uid)
    except Exception as exc:
        print(f"[main] Firestore read error: {exc}")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="No se pudo obtener el historial.",
        )

    return HistoryResponse(messages=messages, total_messages=len(messages))


@app.delete(
    "/history",
    response_model=DeleteResponse,
    tags=["chat"],
    dependencies=[Depends(require_role(["assistant_user", "admin"]))],
)
def delete_history(user: CurrentUser) -> DeleteResponse:
    """Clear message history while preserving the user profile.

    Requires role: ``assistant_user`` or ``admin``.
    """
    try:
        fs.clear_session(user["uid"])
    except Exception as exc:
        print(f"[main] Firestore delete error: {exc}")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="No se pudo borrar el historial.",
        )

    return DeleteResponse(message="Historial borrado exitosamente")


# ---------------------------------------------------------------------------
# Chat endpoints  (subcollection-based: sessions/{uid}/chats/{chat_id})
# ---------------------------------------------------------------------------

@app.get(
    "/chats",
    response_model=ChatListResponse,
    tags=["chat"],
    dependencies=[Depends(require_role(["assistant_user", "viewer", "admin"]))],
)
def list_chats(user: CurrentUser) -> ChatListResponse:
    """Return list of all chats for the authenticated user, newest first."""
    try:
        chats = fs.list_chats(user["uid"])
    except Exception as exc:
        print(f"[main] list_chats error: {exc}")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="No se pudo obtener la lista de chats.",
        )
    return ChatListResponse(chats=chats, total_chats=len(chats))


@app.get(
    "/chats/{chat_id}",
    response_model=ChatHistoryResponse,
    tags=["chat"],
    dependencies=[Depends(require_role(["assistant_user", "viewer", "admin"]))],
)
def get_chat(chat_id: str, user: CurrentUser) -> ChatHistoryResponse:
    """Return messages for a specific chat."""
    try:
        messages = fs.get_chat_messages(user["uid"], chat_id)
    except Exception as exc:
        print(f"[main] get_chat error: {exc}")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="No se pudo obtener el chat.",
        )
    return ChatHistoryResponse(messages=messages, chat_id=chat_id)


@app.delete(
    "/chats/{chat_id}",
    response_model=DeleteResponse,
    tags=["chat"],
    dependencies=[Depends(require_role(["assistant_user", "admin"]))],
)
def delete_one_chat(chat_id: str, user: CurrentUser) -> DeleteResponse:
    """Delete a specific chat."""
    try:
        fs.delete_chat(user["uid"], chat_id)
    except Exception as exc:
        print(f"[main] delete_chat error: {exc}")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="No se pudo eliminar el chat.",
        )
    return DeleteResponse(message="Chat eliminado.")


@app.delete(
    "/chats",
    response_model=DeleteResponse,
    tags=["chat"],
    dependencies=[Depends(require_role(["assistant_user", "admin"]))],
)
def delete_all_chats_endpoint(user: CurrentUser) -> DeleteResponse:
    """Delete all chats for the authenticated user."""
    try:
        fs.delete_all_chats(user["uid"])
    except Exception as exc:
        print(f"[main] delete_all_chats error: {exc}")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="No se pudo eliminar los chats.",
        )
    return DeleteResponse(message="Todos los chats eliminados.")


@app.get(
    "/profile",
    response_model=ProfileResponse,
    tags=["user"],
    dependencies=[Depends(require_role(["assistant_user", "viewer", "admin"]))],
)
def get_profile(user: CurrentUser) -> ProfileResponse:
    """Return the authenticated user's profile."""
    profile = fs.get_user_profile(user["uid"])
    return ProfileResponse(**profile)


@app.put(
    "/profile",
    response_model=ProfileResponse,
    tags=["user"],
    dependencies=[Depends(require_role(["assistant_user", "admin"]))],
)
def update_profile(body: ProfileUpdateRequest, user: CurrentUser) -> ProfileResponse:
    """Update editable profile fields (nombre, preferencias, notas).

    Requires role: ``assistant_user`` or ``admin``.
    """
    updates = {k: v for k, v in body.model_dump().items() if v is not None}
    if updates:
        fs.update_user_profile(user["uid"], updates)
    profile = fs.get_user_profile(user["uid"])
    return ProfileResponse(**profile)


@app.get(
    "/admin/sessions",
    response_model=AdminSessionsResponse,
    tags=["admin"],
    dependencies=[Depends(require_role(["admin"]))],
)
def admin_sessions(user: CurrentUser) -> AdminSessionsResponse:
    """Return a summary of all active sessions (admin dashboard).

    Requires role: ``admin``.
    """
    try:
        sessions = fs.get_all_sessions()
    except Exception as exc:
        print(f"[main] Firestore admin read error: {exc}")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="No se pudieron obtener las sesiones.",
        )

    return AdminSessionsResponse(sessions=sessions, total_sessions=len(sessions))


@app.get(
    "/admin/users",
    response_model=AdminUsersResponse,
    tags=["admin"],
    dependencies=[Depends(require_role(["admin"]))],
)
def admin_list_users() -> AdminUsersResponse:
    """Return all Firebase Auth users with their roles. Requires role: ``admin``."""
    try:
        users = list_firebase_users()
    except Exception as exc:
        print(f"[main] Firebase list_users error: {exc}")
        raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                            detail="No se pudo obtener la lista de usuarios.")
    return AdminUsersResponse(users=users, total_users=len(users))


@app.put(
    "/admin/users/{uid}/role",
    response_model=DeleteResponse,
    tags=["admin"],
    dependencies=[Depends(require_role(["admin"]))],
)
def admin_update_role(uid: str, body: UserRoleUpdateRequest, user: CurrentUser) -> DeleteResponse:
    """Assign or clear a role for a Firebase user. Requires role: ``admin``."""
    if uid == user["uid"] and not body.role:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST,
                            detail="No puedes quitarte el rol a ti mismo.")
    valid = {"assistant_user", "viewer", "admin", None}
    if body.role not in valid:
        raise HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                            detail=f"Rol inválido: {body.role!r}. Válidos: assistant_user, viewer, admin.")
    try:
        set_user_role(uid, body.role)
    except Exception as exc:
        print(f"[main] set_user_role error: {exc}")
        raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                            detail="No se pudo actualizar el rol.")
    return DeleteResponse(message="Rol actualizado correctamente.")


@app.delete(
    "/admin/users/{uid}",
    response_model=DeleteResponse,
    tags=["admin"],
    dependencies=[Depends(require_role(["admin"]))],
)
def admin_delete_user(uid: str, user: CurrentUser) -> DeleteResponse:
    """Permanently delete a Firebase Auth user. Requires role: ``admin``."""
    if uid == user["uid"]:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST,
                            detail="No puedes eliminar tu propia cuenta.")
    try:
        delete_firebase_user(uid)
        fs.clear_session(uid)
    except Exception as exc:
        print(f"[main] delete_user error: {exc}")
        raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                            detail="No se pudo eliminar el usuario.")
    return DeleteResponse(message="Usuario eliminado correctamente.")


# ---------------------------------------------------------------------------
# Static files — prefer built React dist, fall back to raw frontend dir
# Must be mounted LAST so API routes take priority.
# html=True enables SPA fallback (all unknown paths serve index.html).
# No-cache for HTML is handled by _NoCacheHtmlMiddleware above.
# ---------------------------------------------------------------------------
_frontend_dist = Path(__file__).parent.parent / "frontend" / "dist"
_frontend_src = Path(__file__).parent.parent / "frontend"
_serve_dir = _frontend_dist if _frontend_dist.exists() else _frontend_src

app.add_middleware(_NoCacheHtmlMiddleware)

if _serve_dir.exists():
    app.mount("/", StaticFiles(directory=str(_serve_dir), html=True), name="frontend")
